fastlane_require 'dotenv'

before_all do
  Dotenv.overload '.env.secret'
end

default_platform(:ios)
skip_docs

platform :ios do

  desc "Run unit tests"
  lane :test do
    run_tests(scheme: "Sudoku")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    changelog = prompt(
        text: "Changelog: ",
        multi_line_end_keyword: "END"
    )
    puts("Changelog: #{changelog}")

    increment_build_number(build_number: latest_testflight_build_number + 1)
    get_version_number(
      xcodeproj: "Sudoku.xcodeproj",
      target: "Sudoku"
    )
    build_app(
      scheme: "Sudoku",
      export_xcargs: "-allowProvisioningUpdates",
      output_directory: "build"
    )
    add_git_tag(
      tag: "beta/ios/#{lane_context[SharedValues::VERSION_NUMBER]}/#{lane_context[SharedValues::BUILD_NUMBER]}"
    )
    upload_to_testflight(
      demo_account_required: false,
      beta_app_review_info: {
        contact_email: ENV['CONTACT_EMAIL'],
        contact_first_name: ENV['CONTACT_FIRST_NAME'],
        contact_last_name: ENV['CONTACT_LAST_NAME'],
        contact_phone: ENV['CONTACT_PHONE'],
        demo_account_name: "",
        demo_account_password: "",
        notes: "Thank you for reviewing!"
      },
      localized_app_info: {
        "default": {
          feedback_email: ENV['CONTACT_EMAIL'],
          marketing_url: "https://marksinkovics.com/projects/sudoku",
          privacy_policy_url: "https://marksinkovics.com/projects/sudoku/privacy-policy",
          description: "Sudoku - a puzzle game",
        }
      },
      changelog: changelog,
      distribute_external: true,
      groups: ["Private testers"],
    )
    reset_git_repo(
      disregard_gitignore: false
    )
    push_git_tags
  end
end
